blank_issues_enabled: true
contact_links:
  - name: Bug Report
    url: https://github.com/DevExtend/frontend-tarkhineh/issues/new?template=bug_report.md
    about: Report a bug in the project
  - name: Feature Request
    url: https://github.com/DevExtend/frontend-tarkhineh/issues/new?template=feature_request.md
    about: Suggest a new feature or enhancement
